#title[Vehicle Transport Order Settings]

= Differences between vehicle cargo and normal cargo

Vehicle cargo differs from normal cargo in many ways:

+ *Different cargo destination mechanism:* the destination and routing of normal cargo are assigned automatically according to the cargo distribution settings (manual/symmetric/asymmetric) and the cargo flow map generated by the system, while transported vehicles are fully controlled by the player.
+ *Different cargo payment logic:* normal cargo is always paid according to the distance and transport time logic; transporting vehicles within the same company is not charged, while cross-company transport (with shared infrastructure enabled) is charged at the rate configured in the settings.
+ *Completely different underlying logic of the cargo type:* vehicle cargo stores vehicle information.
+ ……

Because of these differences, orders for transporting normal cargo are not compatible with orders for transporting vehicles.

= Loading options

Once a vehicle is refitted to a carrier vehicle, the loading/unloading settings for vehicle transport will be listed above those for normal cargo, as shown:

#figure(
  image("../../static/images/veh-carry-load-order.png", width: 80%),
)

== Option explanations

Options in the menu:

#table(
  columns: 2,
  [*Name*], [*Effect*],
  [Load any vehicles], [Load all vehicles waiting at this station],
  [Load vehicles going to the next stop], [Load the vehicles waiting here whose next order entry is the same as the carrier's next order entry],
  [Wait for vehicles], [When no vehicle is waiting here, wait for at least one vehicle to board#linebreak()_Only available when the order is Load vehicles_],
  [Vehicles loading options...], [Open the vehicle transport window to apply more restrictions, see the table below#linebreak()_Only available when the order is Load vehicles_],
)

Options in the vehicle transport window:

#table(
  columns: 2,
  [*Name*], [*Effect*],
  [Load state], [Restrict the loaded vehicles to `empty only`/`full only`],
  [Cargo], [Restrict the cargo carried by the vehicles being loaded],
  [Cargo criterion], [Must be used together with the previous option.#linebreak()`must be able to carry` — the carried vehicle must be able to load the specified cargo type#linebreak()`must be carrying` — the carried vehicle must currently be loading the specified cargo type (load amount not equal to 0)],
  [Minimum waiting time], [Restrict the minimum time the loaded vehicles must have waited at the loading station],
  [Trace restrict slot], [Restrict the slot (token) of the vehicles being loaded],
  [Most vehicles at once], [Restrict the maximum number of vehicles that can be loaded at the same time]
)

= Unloading options

#figure(
  image("../../static/images/veh-carry-unload-order.png", width: 80%),
)

#table(
  columns: 2,
  [*Name*], [*Effect*],
  [Unload vehicles], [Unload the vehicles that need to be unloaded at this station],
  [Unload all vehicles], [Try to unload all vehicles at this station, unless restricted by external factors such as no available station],
)

When unloading, the vehicle will search all available platforms of the unloading station and unload at the platform closest to the next destination.
