name: Build Docs

on:
  workflow_dispatch:

defaults:
  run:
    working-directory: ./pxp-docs

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Install Typst
        uses: typst-community/setup-typst@v3
        with:
          typst-version: "0.15.1"

      - name: Build docs
        run: typst compile --features bundle,html --format bundle main.typ dist

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist

  deploy:
    needs: build-docs
    runs-on: ubuntu-latest
    environment:
      name: github-pages
    steps:
      - uses: actions/deploy-pages@v5
